baseurl: "/"
relativeurls: true
languageCode: "en-us"
title: "The title of your website"
theme: "hugo-lithium-theme"
googleAnalytics: ""
disqusShortname: ""
ignoreFiles: ["\\.Rmd$", "_files$", "_cache$"]
hasCJKLanguage: true
enableEmoji: true
footnotereturnlinkcontents: "↩"

permalinks:
  cn: "/cn/:year/:month/:slug/"
  en: "/en/:year/:month/:slug/"

menu:
  main:
    - name: "About"
      url: "/en/about/"
      weight: 0
    - name: "Blog"
      url: "/en/"
      weight: 1
    - name: "关于"
      url: "/cn/about/"
      weight: 2
    - name: "博客"
      url: "/cn/"
      weight: 3
  en:
    - name: "Home"
      url: "/"
      weight: 0
    - name: "About"
      url: "/en/about/"
      weight: 1
    - name: "Blog"
      url: "/en/"
      weight: 2
    - name: "Vitae"
      url: "/en/vitae/"
      weight: 3
    - name: "中文"
      url: "/cn/"
      weight: 4
  cn:
    - name: "首页"
      url: "/"
      weight: 0
    - name: "关于"
      url: "/cn/about/"
      weight: 1
    - name: "博客"
      url: "/cn/"
      weight: 2
    - name: "简历"
      url: "/cn/vitae/"
      weight: 3
    - name: "English"
      url: "/en/"
      weight: 4
  cool:
    - name: "Home"
      url: "/"
      weight: 0
    - name: "Project Home"
      url: "/cool/"
      weight: 1
    - name: "Sample Page"
      url: "/cool/sample/"
      weight: 2
    - name: "Github repo"
      pre: "github"
      url: "https://github.com/yihui/blogdown-yihui-template"
      weight: 3

params:
  description: "Description of your website."
  disqusURL: "http://yihui.name"
  fullURL: "https://yihui.name"
  customCSS: ["css/custom.css"]
  customJS: ["js/center-img.js", "js/right-quote.js", "js/no-highlight.js", "js/fix-footnote.js"]
  githubContentURL: "https://github.com/rbind/yihui.name/edit/master/content/"

  # options for highlight.js (version, additional languages, and theme)
  highlightjsVersion: "9.9.0"
  highlightjsLang: ["r", "yaml", "tex"]
  highlightjsTheme: "github"

  social:
    twitter: "xieyihui"
    weibo: "谢益辉"
    weibo_url: "yihuixie"
    github: "yihui"

  logo:
    url: "logo.png"
    width: 50
    height: 50
    alt: "Yihui Xie"

  author:
    en: "Yihui Xie"
    cn: "谢益辉"

  lang:
    edit:
      en: "Suggest an edit of this page"
      cn: "编辑本页"

blackfriday:
    extensionsmask: ["noIntraEmphasis"]
